### ISSUE TITLE
UI suggestions

### ISSUE THREAD

**Issue by l3d00m** [l3d00m/pietsmiet_android#27]
Gesammelte, unsortierete und ungefilterte Ideen (danke @Gambleon )

* [ ] Farben der Karten verändern
* [x] Uploadplan verändern, sodass weniger Leerzeilen
* [x] Grün für Switches zu hell
* [ ] App Icon
* [x] Einheitliche grüne Farbe (Hintergrundfarbe?)
* [x] Auch das Ladesymbol
* [ ] Symbol (Facebook, Twitter, ...) hinzufügen für schnellere Unterscheidung
* [ ] Schriftgröße kleiner
* [ ] Titel anstatt Karten färben

**Comment by Bluscream** [comment]
Dunkles Design
