### ISSUE TITLE
Benachrichtigungen mit Firebase

### ISSUE THREAD

**Issue by l3d00m** [l3d00m/pietsmiet_android#3]
für:
- [x] PietCast

- [x] Uploadplan
- [x] Edit: Uploadplan in Firebase Database speichern, um unnötige Belatung zu vermeiden.

**Comment by julian-villing** [comment]
Alles! (Nach Wunsch)

**Comment by l3d00m** [comment]
Da die API leider gecancelt wurde, werden wir das RSS-Fetching für die Benachrichtigungen über einen seperaten Server laufen lassen, um die Last auf pietsmiet.de zu minimieren. Dieser wird dann per Firebase Messaging die Nutzer benachrichtigen.

**Comment by l3d00m** [comment]
See https://github.com/l3d00m/pietsmiet_android/tree/firebase

**Comment by l3d00m** [comment]
Done with d410b493562fb98ae928a50d5effa8ee234f60cf
