### ISSUE TITLE
compiled apk?

### ISSUE THREAD

**Issue by Bluscream** [l3d00m/pietsmiet_android#36]

**Comment by l3d00m** [comment]
Moin,

da die App noch pre Alpha ist laden wir die nur gelegentlich in die Dropbox hoch, [Link hier](https://www.dropbox.com/s/yvnzfsxy46416j6/app-debug.apk?dl=1). Ist weder vom Design noch von den Features her fertig :) (und glaub ich schon nen moment älter, werd die die Tage mal updaten)

**Comment by Bluscream** [comment]
Danke, warum nicht als github prerelease wenns dafür eh schon ne repo gibt?

**Comment by l3d00m** [comment]
Kommt sobald es auch nen prerelease gibt. Die Version in der dropbox ist eigentlich nur für uns entwickler zum testen gedacht und ist noch nichtmal prerelease
