### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by Bluscream** [l3d00m/pietsmiet_android#37]
Could you add a "how to build" section to the readme? It seems like you're using something different than Android studio.

btw. Grüß mal bitte Timo der heute geburtstag hat in ner benachrichtigung :D

**Comment by l3d00m** [comment]
Kannst auch gerne auf Deutsch schreiben, hier ist eh alles Englisch Deutsch Mischung 😄 

Nen How to Build erachte ich als nicht sinnvoll, weil es unabhängig von der Android Version klappen sollte. Was ist denn dein Problem?

**Comment by Bluscream** [comment]
Naja hab nur die gradle dateien gesehen und gedacht das man dafür jz gradle brauch

**Comment by l3d00m** [comment]
Nur Android Studio

**Comment by Bluscream** [comment]
Ah okay super das werd ich probieren, gibts eig, news zur ps.de api? Gibts die wieder, oder ne neue? Oder muss man jetzt doch alles aus der html auslesen?

**Comment by l3d00m** [comment]
Die wird's nicht geben, wir lesen zumindest die Uploadpläne aus dem HTML raus und den Rest wird's nicht geben (nicht gewollt)
