### ISSUE TITLE
Pietcast feed doppelt?

### ISSUE THREAD

**Issue by Bluscream** [l3d00m/pietsmiet_android#38]
Warum wird der feed von 2 Urls geholt?

![](https://puu.sh/vetfq/582f2cb4b8.jpg)

**Comment by l3d00m** [comment]
Welche branch benutzt du? `develop` oder `Endless-Scroll`?

**Comment by l3d00m** [comment]
Und änder mal in Zeile 17 (Pietcast-Presenter) von pietcast.de auf pietsmiet.de und guck ob das Problem besteht

**Comment by Bluscream** [comment]
Kann ich das in der app irgendwo sehen?

![](https://puu.sh/vetoi/45572d3e7f.png)

**Comment by l3d00m** [comment]
Ach sorry, ich dachte du hättest dir das direkt gebuildet

**Comment by Bluscream** [comment]
Das war auch mehr eine frage als ein bugreport. Wusste garnicht das es pietcast.de gibt. Ist das 3rd party?

**Comment by l3d00m** [comment]
Die gabs vor der ps.de

**Comment by Bluscream** [comment]
Ah okay, super danke. Ist das dann jetzt ne weiterleitung zu ps.de oder holt sich die app einfach beides?

**Comment by l3d00m** [comment]
Ich denke das ist die Weiterleitung, deshalb auch meine Frage ob du das ersetzen kannst.

**Comment by Bluscream** [comment]
Naja bin grad am tablet und soweit ich weiss kann man da nix compilen :D

![](https://puu.sh/vetXV/a557590e0c.png)
