### ISSUE TITLE
Auto expand

### ISSUE THREAD

**Issue by Bluscream** [l3d00m/pietsmiet_android#45]
It would be nice if the posts would auto expand if
- only one post is displayed (https://puu.sh/viXGy/e5eeba374e.png)
- all posts displayed are from the same category

**Comment by julian-villing** [comment]
Man könnte bei einem einzigen Post sogar den Expander-Button verstecken und automatisch expanden, denn was will ich denn sonst, wenn ich auf die Notification drauf klicke? xD

**Comment by l3d00m** [comment]
Alternativ: Bei Uploadplan nur den Plan anzeigen und bei Ausklappen alles (Einleitung)

**Comment by l3d00m** [comment]
Alternativ #2: Uploadplan immer ausklappen, mittlerweile ist der unnötige Whitespace auch raus

**Comment by l3d00m** [comment]
Fixed with https://github.com/l3d00m/pietsmiet_android/commit/b30a5a7bbc2179280424c5f023d25dc98e25c176
