### ISSUE TITLE
Leere Zeilen aus Uploadplan entfernen

### ISSUE THREAD

**Issue by julian-villing** [l3d00m/pietsmiet_android#46]
**Überspitzt**

- [x] Wer braucht 3 Leerzeilen ?
- [x] Wer möchte in der Notification den Einleitungstext anstelle des Uploadplans lesen?

**Comment by saibotk** [comment]
das mit der Notification liegt am guten Sven. Der formatiert anders ;) 
Ansonsten klar Leerzeilen werde ich entfernen.

**Comment by julian-villing** [comment]
Tuts nicht.

Früher stand in der Notification
HH:MM PS.de / HH:MM YT: $videoTitle

Jetzt (gestern/heute) steht da:
$boringIntroductionText

**Comment by saibotk** [comment]
Eh doch, wie gesagt @l3d00m meinte das liegt an der anderen Formatierung -> Code Änderung erforderlich.

**Comment by l3d00m** [comment]
Benachrichtigung ist gefixt in https://github.com/l3d00m/pietsmiet_xposter/commit/6adaccb8051b0df543a4840decc67bbf8d4986c4

**Comment by l3d00m** [comment]
https://github.com/l3d00m/pietsmiet_xposter/commit/6715e90779804a408e6035f5ccec79a83a850655

**Comment by l3d00m** [comment]
Und noch weiter verbessert: https://github.com/l3d00m/pietsmiet_xposter/commit/e00c9a9bcdc17e3aeda9d93bcc5931c26e0e4ccf
