### ISSUE TITLE
Videoplayer mit Videos der Website

### ISSUE THREAD

**Issue by l3d00m** [l3d00m/pietsmiet_android#5]
sobald Website das unterstützt

**Comment by Grob98** [comment]
Kann man da nicht die YouTube API nutzen?

**Comment by l3d00m** [comment]
Könnte man eigentlich auch. Ich würde dann allerdings vorschlagen, nur zur YouTube-App zu verlinken, da die YouTube api nicht die beste ist.

**Comment by Hecke29** [comment]
Unter http://www.pietsmiet.de/index.php?option=com_hwdmediashare&task=media&format=feed&type=mrss&limitstart=0&list[limit]=10&list[fullordering]=created%20DESC (es ist NICHT der gleiche wie auf reddit) kann man die letzten limit=3 Einträge soriert nach created abrufen.

Man bekommt für jedes Video, das auf PietSmiet gehostet ist mehrere Media-Links (für die Auflösungen). Für YouTube-Videos die YouTube-URL.

Nice to now: PubDate ist nicht das Veröffentlichungsdatum des Videos. Ich vermute es ist der Upload-Zeitpunkt.

Mein Plan ist es eine JSON-API zur Verfügung zu stellen, die genau solche Quellen aggregiert und aufarbeitet und dann zentral zur Verfügung stellt. Die pietsmiet.de ist nämlich auch nicht unbedingt die schnellste.

**Comment by l3d00m** [comment]
Vielen Dank für die Links und die Infos nochmals. Ich werde die testen, sobald die Website mal wieder funktioniert :/

Eine JSON-API wäre mit Abstand das einfachste und beste für uns und wurde uns ne Menge Arbeit ersparen. Würdest du die dann auf github veröffentlichen? Mich würde mal interessieren, wie so etwas überhaupt funktioniert.

**Comment by Hecke29** [comment]
Wird wohl ein public github repo werden, ja.

Ich lasse dir den Link die Tage zukommen.

**Comment by Hecke29** [comment]
Die Schnittstellen wurden durch PietSmiet entfernt. Keine Feeds mehr verfügbar. (s. https://www.reddit.com/r/PietSmiet/comments/58027y/pietsmietde_gegen_fortschritt_weiterentwicklung/)

Mein Projekt wird nicht auf github veröffentlicht werden.

**Comment by l3d00m** [comment]
Vermutlich wird dieses Feature nie impklementiert, da Team PS damit wahrscheinlich nicht einverstanden wäre.
