### ISSUE TITLE
Subreddit Posts anzeigen?

### ISSUE THREAD

**Issue by saibotk** [l3d00m/pietsmiet_android#54]
Idee von Em#1264

**Comment by julian-villing** [comment]
Find ich eine gute Idee, aber ich denke man sollte die anderen Features (Auto Expand, ...) erst lauffähig (oder gleich fertig) machen, bevor man neue coole aber optionale Features einfügt

**Comment by saibotk** [comment]
@Gambleon war auch mehr ein Reminder als ein "sofort" High Priority NEEDED feature ;)

**Comment by l3d00m** [comment]
Ich finde Subreddit-Posts passen da nicht rein, weil das ja von Nutzern kommt. Wir zeigen nur Content an, der vom Team PS erstellt wurde.
