### ISSUE TITLE
Adapter bug: associates images wrong

### ISSUE THREAD

**Issue by saibotk** [l3d00m/pietsmiet_android#65]
Images sometimes, while scolling down fast,
will be shown on other posts too.
Sometimes even posts without an image, will receive one.
This fixes itself if you keep scrolling until the View gets recycled.

**Comment by l3d00m** [comment]
Fixed with https://github.com/l3d00m/pietsmiet_android/commit/10395e0b23b2df7f8f50cef4cede70a8f26711bc
