### ISSUE TITLE
Trennline nach jedem Tag

### ISSUE THREAD

**Issue by l3d00m** [l3d00m/pietsmiet_android#66]
Auf Vorschlag von unserem Designmeister. So ähnlich wie zB Disocrd das macht

**Comment by julian-villing** [comment]
Dann würde ich die Karten aber inline (flat) machen, weil es sonst doppelt-gemoppelt und mMn vmtl. zu viel des Guten ist.

**Comment by saibotk** [comment]
Hier geht es nicht um die CardViews. Danke
