### ISSUE TITLE
(Chrome) Custom Tabs statt extern öffnen

### ISSUE THREAD

**Issue by l3d00m** [l3d00m/pietsmiet_android#88]
Wenn Custom Tabs durch das Gerät unterstützt werden (durch vorhandes Chrome oder Firefox), Links in diesem öffnen anstatt extern. Vorteil: Deutlich schnelleres und komfortableres Öffnen.

WebView lieber nicht, da es langsam und verbuggt ist

https://developer.chrome.com/multidevice/android/customtabs

**Comment by saibotk** [comment]
Gut das wie gar keine WebView haben lieber @l3d00m

**Comment by l3d00m** [comment]
Ich wollte nur sagen, dass wir mit WebView erst gar nicht anfangen
