### ISSUE TITLE
Fix failing tests

### ISSUE THREAD

**Issue by l3d00m** [l3d00m/pietsmiet_android#92]
Tests are failing out of nowhere without touching the code, restarting old successful travis builds fails them as well, I have no idea what's going on.

**Comment by julian-villing** [comment]
Any library updated/relevant code changed back to when they sill worked?

**Comment by l3d00m** [comment]
Old commits that worked previously do now fail, so the code hasn't changed

**Comment by saibotk** [comment]
fixed in 2eb80d3
